[package]
name = "evetech"
version = "0.2.2"
edition = "2021"

[dependencies]
    anyhow = "1.0"
    log = "0.4"
    env_logger = "0.11"
    reqwest = { version = "0.11", features = ["json"] }
    serde = { version = "1.0", features = ["derive"] }
    serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
    serde_derive = { version = "1.0" }
    tokio = { version = "1", features = ["full"] }
    docopt = "1.1"
    septem = "1.1.0"
    itertools ="0.12"

[dev-dependencies]
    approx = "0.5"
    env_logger = { version = "0.11", default-features = false }
