[package]
name = "evetech"
version = "0.2.5"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_derive = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
docopt = "1.1"
septem = "1.1"
itertools = "0.12"
diesel = { version = "2.2.0", features = ["sqlite", "chrono"] }
dotenvy = "0.15"
chrono = "*"
# actix = "0.13.0"
# actix-rt = { version = "2.6.0", default-features = false }
actix-web = { version = "4" }
# actix-http = "3.1.0"
# actix-files = "0.6.1"
# actix-cors = "0.6.1"
# actix_derive = { version = "0.6.0", optional = true }


[dev-dependencies]
approx = "0.5"
diesel_migrations = "2.0"
